name: (Re)initialize Deployment
run-name: (Re)initialize Deployment by ${{ github.actor }}

on:
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  VENV: "venv"
  PYTHON: "3.12"

jobs:
  clean-up-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Existing Folder
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf ${{ env.REPO_NAME }} && mkdir ${{ env.REPO_NAME }}
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-tt"

  setup-python:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pip and venv
        uses: fifsky/ssh-action@master
        with:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get install -y python3-pip python3-venv
            pip --version
            source ${{env.REPO_NAME}}/source/bin/activate
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-tt"
  
  deploy-via-sftp:
    needs: [ clean-up-folder, setup-python ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.VPS_USER }}
          server: ${{ secrets.VPS_IP }}
          port: ${{secrets.PORT}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # clones entire github repo
          local_path: ./*
          # destination of the code on the server
          remote_path: ./${{ env.REPO_NAME }}
          sftpArgs: '-o ConnectTimeout=15'

  install-requirements:
    needs: [ deploy-via-sftp ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Requirements
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ env.REPO_NAME }}
            python3 -m venv ${{env.VENV}}
            source ${{env.VENV}}/bin/activate
            pip install --upgrade pip
            pip install -U -r ./requirements.txt
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-tt"

  add-secret-variables:
    needs: [deploy-via-sftp]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - id: add-secret-variables
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ env.REPO_NAME }}
            echo "DISCORD_API_TOKEN=${{ secrets.DISCORD_API_TOKEN }}" > .env
            echo "DISCORD_API_TOKEN_TEST=${{ secrets.DISCORD_API_TOKEN_TEST }}" >> .env
            echo "REFER_DB=${{ secrets.REFER_DB }}" >> .env
            echo "CARHUNT_DB=${{ secrets.CARHUNT_DB }}" >> .env
            echo "CLASH_DB=${{ secrets.CLASH_DB }}" >> .env
            echo "ELITE_DB=${{ secrets.ELITE_DB }}" >> .env
            echo "WEEKLY_DB=${{ secrets.WEEKLY_DB }}" >> .env
            echo "CAR_LIST_DB=${{ secrets.CAR_LIST_DB }}" >> .env
            echo "FEEDBACK_LOG_CHANNEL=${{ secrets.FEEDBACK_LOG_CHANNEL }}" >> .env
            echo "SUGGESTION_CHANNEL=${{ secrets.SUGGESTION_CHANNEL }}" >> .env
            echo "ERROR_LOG_WH=${{ secrets.ERROR_LOG_WH }}" >> .env
            echo "FEEDBACK_WH=${{ secrets.FEEDBACK_WH }}" >> .env
            echo "LOG_WH=${{ secrets.LOG_WH }}" >> .env
            echo $?
          host: ${{ env.VPS_IP }}
          user: ${{ env.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
  
  create-systemctl-service:
    needs: [add-secret-variables, install-requirements]
    runs-on: ubuntu-latest
    steps:
      - id: creating-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          # Make sure ExecStart=, WorkingDirectory= and chmod +x point to the same directory. These may be unique to your code setup
          command: |
            sudo bash -c 'echo "[Unit]
            Description=${{ env.REPO_NAME }} Discord Bot
            After=multi-user.target
            [Service]
            Type=simple
            ExecStart=$(pwd)/venv/bin/python3 $(pwd)/venv/${{ env.REPO_NAME }}/launcher.py -normal
            User=${{ env.VPS_USER }}
            Restart=on-failure
            RestartSec=30
            WorkingDirectory=$(pwd)/venv/${{ env.REPO_NAME }}/
            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/${{ env.REPO_NAME }}.service'
            chmod +x $(pwd)/venv/${{ env.REPO_NAME }}/launcher.py
            sudo systemctl enable ${{ env.REPO_NAME }}.service
            sudo systemctl daemon-reload
            sudo systemctl start ${{ env.REPO_NAME }}.service
          host: ${{ env.VPS_IP }}
          user: ${{ env.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
    
  create-systemctl-restart:
    needs: [create-systemctl-service]
    runs-on: ubuntu-latest
    steps:
      - id: create-systemctl-restart-service
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo bash -c 'echo "[Unit]
            Description=${{ env.REPO_NAME }} Discord Bot restart
            After=multi-user.target
            [Service]
            Type=oneshot
            ExecStart=/usr/bin/systemctl restart ${{ env.REPO_NAME }}.service
            [Install]
            WantedBy=multi-user.target" > /etc/systemd/system/${{ env.REPO_NAME }}-watcher.service'
            sudo systemctl enable ${{ env.REPO_NAME }}-watcher.service
            sudo systemctl daemon-reload
            sudo systemctl start ${{ env.REPO_NAME }}-watcher.service
          host: ${{ env.VPS_IP }}
          user: ${{ env.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}