name: Initialize pip and venv
on:
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  setup-requirements:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Setup pip and venv
        uses: fifsky/ssh-action@master
        with:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get install -y python3-pip python3-venv
            echo "pip installation completed"
            exit 0
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}