name: Update Bot
on:
  push:
    branches: [ production ]
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@master
        with:
          username: ${{ secrets.VPS_USER }}
          server: ${{ secrets.VPS_IP }}
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./*
          remote_path: /venv/${{ env.REPO_NAME }}/
          args: '-o ConnectTimeout=5'

  restart-bot:
    needs: [deploy-via-sftp]
    runs-on: ubuntu-latest
    steps:
      - id: creating-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          command: sudo systemctl start ${{ env.REPO_NAME }}-watcher.service
          host: ${{ secrets.VPS_IP }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}